-- vim.o.signcolumn = 'number'
vim.diagnostic.config({ virtual_text = true })
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.g.markdown_recommended_style = 0 -- Fix markdown indentation settings
vim.g.netrw_banner = 0
vim.g.netrw_localrmdir = 'rm -r'
vim.g.netrw_winsize = 25
vim.o.autowrite = true -- Enable auto write
vim.o.backup = false
vim.o.clipboard = 'unnamedplus' -- Sync with system clipboard
vim.o.cmdheight = 1
vim.o.colorcolumn = '+0'
vim.o.completeopt = 'menuone,noselect'
vim.o.confirm = true -- Confirm to save changes before exiting modified buffer
vim.o.cursorline = true -- Enable highlighting of the current line
vim.o.errorbells = false
vim.o.expandtab = true -- Use spaces instead of tabs
vim.o.formatoptions = 'jcroqlnt' -- tcqj
vim.o.grepformat = '%f:%l:%c:%m'
vim.o.grepprg = 'rg --vimgrep'
vim.o.guifont = 'MonoLisa:h14'
vim.o.hlsearch = false
vim.o.ignorecase = true -- Ignore case
vim.o.inccommand = 'nosplit' -- preview incremental substitute
vim.o.incsearch = true
vim.o.laststatus = 0
vim.o.list = true -- Show some invisible characters (tabs...
vim.o.mouse = 'a' -- Enable mouse mode
vim.o.nu = true
vim.o.number = true -- Print line number
vim.o.pumblend = 10 -- Popup blend
vim.o.pumheight = 10 -- Maximum number of entries in a popup
vim.o.relativenumber = true -- Relative line numbers
vim.o.scrolloff = 4 -- Lines of context
vim.o.sessionoptions = 'buffers,curdir,tabpages,winsize'
vim.o.shiftround = true -- Round indent
vim.o.shiftwidth = 4 -- Size of an indent
vim.o.showmode = false -- Dont show mode since we have a statusline
vim.o.sidescrolloff = 4 -- Columns of context
vim.o.signcolumn = 'yes:2' -- Always show the signcolumn, otherwise it would shift the text each time
vim.o.smartcase = true -- Don't ignore case with capitals
vim.o.smartindent = true -- Insert indents automatically
vim.o.softtabstop = 2
vim.o.splitbelow = true -- force all horizontal splits to go below current window
vim.o.splitright = true -- force all vertical splits to go to the right of current window
vim.o.swapfile = false
vim.o.tabstop = 2 -- Number of spaces tabs count for
vim.o.termguicolors = true -- True color support
vim.o.textwidth = 80
vim.o.timeoutlen = 300
vim.o.undodir = os.getenv('HOME') .. '/.vim/undodir'
vim.o.undofile = true
vim.o.undolevels = 10000
vim.o.updatetime = 50
vim.o.wildmode = 'longest:full,full' -- Command-line completion mode
vim.o.wildoptions = 'fuzzy'
vim.o.winminwidth = 5 -- Minimum window width
vim.o.wrap = false -- Disable line wrap
vim.opt.isfname:append('@-@')
vim.opt.shortmess:append('c')
vim.opt.shortmess:append({ W = true, I = true, c = true })
